watch_stylesheet: true
watch_config: true
debug: false

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["home", "glazewm_workspaces", "active_window"]
      center: ["notifications", "clock", "pomodoro"]
      right: ["media", "wifi", "microphone", "volume", "power_menu"]
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      rewrite:
        # Clean up Visual Studio Code titles
        - pattern: "^(.+) - (.+) - Visual Studio Code$"
          replacement: "Visual Studio Code - \\1"
        - pattern: "^(.+) - Visual Studio Code$"
          replacement: "Visual Studio Code - \\1"

        # Strip trailing ".exe" (case-insensitive) and lowercase
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
          case: lower

        # General cleanup for other apps if needed
        - pattern: "^(.+) - (.+) - (.+)$"
          replacement: "\\3 - \\1"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue8e5</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "C:\\Users\\Vishvaa\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\Vishvaa\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\Vishvaa\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#585b70"
      distance: 6
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title} - {artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 35
        label_alt: 60
      show_thumbnail: false
      controls_only: false
      controls_left: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "#585b70"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 10
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a %d %b %I:%M %p}"
      label_alt: "{%A %d %B %Y %I:%M:%S %p}"
      timezones: []
    calendar:
      blur: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "#585b70"
      alignment: "center"
      direction: "down"
      distance: 6
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: false
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "#585b70"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#1e1e2e"
        circle_work_progress_color: "#a6e3a1"
        circle_break_progress_color: "#89b4fa"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 5
        bottom: 0
        right: 5
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: " time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec explorer ms-availablenetworks:"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {ip_addr}"
      ethernet_icon: "\uef44"
      wifi_icons:
        [
          "\udb82\udd2e",
          "\udb82\udd1f",
          "\udb82\udd22",
          "\udb82\udd25",
          "\udb82\udd28",
        ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: ""
      update_interval: 600
      hide_decimal: true
      location: "India New Delhi 90006"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      icons:
        normal: "\uf130"
        muted: "\uf131"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\udb81\udf5f "
        - "\uf026 "
        - "\uf026 "
        - "\uf027 "
        - "\uf028 "
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 200
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf0f3</span> {count}"
      label_alt: "Notifications: {count}"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_middle: "clear_notifications"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
